// <auto-generated />
namespace TrekStories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequiredAttributeForNonNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiredAttributeForNonNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201807052139563_RequiredAttributeForNonNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
